### ISSUE TITLE
[S1 - PBI18] Pengembangan fitur user journal history

### ISSUE THREAD

**Issue by zeinalwi** [SI-RPL-2021/SI4201-You_Counsel#19]
Sebagai user, saya dapat melihat journal history agar dapat mengontrol keadaan saya sendiri

**Comment by ariafajarr14** [comment]
![UserJournalHistory](https://user-images.githubusercontent.com/45222094/119943271-021b4d80-bfbd-11eb-9a51-6be9ccb8ec06.png)
