### ISSUE TITLE
[S3 - PBI26] (Back End) Konselor - Pengembangan fitur jurnal

### ISSUE THREAD

**Issue by alyaarifahrizqy** [SI-RPL-2021/SI4201-You_Counsel#37]
Flow:
-Konselor dapat memasukkan username client
-Konselor dapat melihat jurnal client

![JournalChecker](https://user-images.githubusercontent.com/71878744/121181177-ec930700-c88b-11eb-92fb-bed338252c64.png)
![JournalChecker2](https://user-images.githubusercontent.com/71878744/121181198-f288e800-c88b-11eb-852b-c3e4dac9fa2b.png)

**Comment by todosantana** [comment]
Penggunaan ID dianggap kurang efektif, diganti menggunakan username client
