### ISSUE TITLE
[S1 - PBI6] Pengembangan fitur pemberitahuan pesan masuk

### ISSUE THREAD

**Issue by Ikaprisilia** [SI-RPL-2021/SI4201-You_Counsel#5]
Sebagai user saya dapat menerima pemberitahuan pesan yang masuk

**Comment by Ikaprisilia** [comment]
![Inbox](https://user-images.githubusercontent.com/71888971/112872527-afbbce80-90ea-11eb-960d-0052c0147356.png)

**Comment by tienfkusumasari** [comment]
belum ngambil data dari database, salah mockup

**Comment by Ikaprisilia** [comment]
![Inbox](https://user-images.githubusercontent.com/71888971/116153772-0d573100-a712-11eb-8600-21c8166c03a2.png)
![Inbox Message](https://user-images.githubusercontent.com/71888971/116153790-12b47b80-a712-11eb-843d-4e6445e9e05a.png)
